<a href="https://colab.research.google.com/github/sahilm11/sayana/blob/master/wine_type_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [0]:
import pandas as pd

In [0]:
#white wine data
white = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=';')

In [0]:
#red wine data
red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')

In [5]:
red.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [0]:
white['type']=0

In [0]:
red['type']=1

In [0]:
wines=white.append(red, ignore_index=True)

In [0]:
winesFeatures=wines.loc[:,wines.columns != 'type']

In [0]:
winesTarget=wines.iloc[:,-1]

In [11]:
wines.iloc[:,-1]

0       0
1       0
2       0
3       0
4       0
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: type, Length: 6497, dtype: int64

In [12]:
winesTarget.describe()

count    6497.000000
mean        0.246114
std         0.430779
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: type, dtype: float64

In [0]:
x=winesFeatures

In [0]:
y=np.ravel(wines.type)

In [0]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.33, random_state=42)

In [0]:
scaler = StandardScaler().fit(x_train)

In [0]:
x_train = scaler.transform(x_train)

In [0]:
x_test = scaler.transform(x_test)

In [19]:
from  keras.models import Sequential

Using TensorFlow backend.


In [0]:
from keras.layers import Dense

In [0]:
model=Sequential()

In [0]:
model.add(Dense(12, activation='relu', input_shape=(12,)))

In [0]:
model.add(Dense(8,activation='relu'))

In [0]:
model.add(Dense(1,activation='sigmoid'))

In [25]:
model.output_shape

(None, 1)

In [26]:
model.summary

<bound method Network.summary of <keras.engine.sequential.Sequential object at 0x7f1ab77e2518>>

In [27]:
model.get_config()

{'layers': [{'class_name': 'Dense',
   'config': {'activation': 'relu',
    'activity_regularizer': None,
    'batch_input_shape': (None, 12),
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'VarianceScaling',
     'config': {'distribution': 'uniform',
      'mode': 'fan_avg',
      'scale': 1.0,
      'seed': None}},
    'kernel_regularizer': None,
    'name': 'dense_1',
    'trainable': True,
    'units': 12,
    'use_bias': True}},
  {'class_name': 'Dense',
   'config': {'activation': 'relu',
    'activity_regularizer': None,
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'VarianceScaling',
     'config': {'distribution': 'uniform',
      'mode': '

In [28]:
model.get_weights()

[array([[-0.15442085,  0.19295812, -0.00166142, -0.13877094, -0.1393249 ,
          0.46470678,  0.17304075,  0.11547482,  0.10406876,  0.39162016,
          0.22684312,  0.0636512 ],
        [ 0.13881576,  0.2448169 , -0.39762795, -0.11163449,  0.31034172,
          0.0594691 ,  0.15658987,  0.24012363,  0.23708272, -0.42676258,
          0.2500701 ,  0.09148371],
        [ 0.08458483, -0.41736197,  0.15223908, -0.04213417,  0.19831395,
         -0.21639168, -0.44255865,  0.37818074,  0.412771  ,  0.06807756,
          0.4316517 , -0.3406018 ],
        [ 0.11707675, -0.1480658 ,  0.07334054,  0.49883866, -0.23038149,
          0.25586092,  0.41182697, -0.49453974, -0.08669555, -0.0723418 ,
         -0.4520992 , -0.47261858],
        [ 0.10899687,  0.11820531, -0.28517568, -0.03724933, -0.48559856,
          0.15131688, -0.14592922, -0.4985664 , -0.2633922 , -0.02354765,
         -0.3917699 , -0.10757339],
        [ 0.17813516,  0.4096049 , -0.35092247,  0.12886631,  0.14281595,
      

In [0]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
model.fit(x_train, y_train, epochs=20, batch_size=1, verbose=1)

Epoch 1/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.1154 - accuracy: 0.9614
Epoch 2/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0246 - accuracy: 0.9956
Epoch 3/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0209 - accuracy: 0.9961
Epoch 4/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0171 - accuracy: 0.9961
Epoch 5/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0163 - accuracy: 0.9966
Epoch 6/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0152 - accuracy: 0.9968
Epoch 7/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0151 - accuracy: 0.9970
Epoch 8/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0136 - accuracy: 0.9972
Epoch 9/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0133 - accuracy: 0.9972
Epoch 10/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.013

In [0]:
y_pred=model.predict(x_test)

In [32]:
y_pred[:5]

array([[1.6839802e-02],
       [1.3715029e-04],
       [8.3579891e-07],
       [5.8212134e-08],
       [2.2968958e-07]], dtype=float32)

In [33]:
y_test[:5]

array([0, 0, 0, 0, 0])

In [0]:
y_pred1=np.round(y_pred)

In [35]:
y_pred1

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [36]:
score=model.evaluate(x_test, y_test, verbose=1)

2145/2145 [==============================] - 0s 31us/step


In [37]:
print(score)

[0.05153430737393904, 0.9953380227088928]


In [0]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score


In [39]:
confusion_matrix(y_test, y_pred1)

array([[1623,    1],
       [  91,  430]])

In [40]:
precision_score(y_test, y_pred1)

0.9976798143851509

In [41]:
recall_score(y_test, y_pred1)

0.8253358925143954

In [42]:
f1_score(y_test,y_pred1)

0.9033613445378152

In [43]:
cohen_kappa_score(y_test, y_pred1)

0.8761157056960158

In [44]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [45]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
y_pred

array([[1.6839802e-02],
       [1.3715029e-04],
       [8.3579891e-07],
       ...,
       [3.2117948e-06],
       [1.3953447e-04],
       [8.3651903e-05]], dtype=float32)

In [47]:
y

array([0, 0, 0, ..., 1, 1, 1])